#!/usr/bin/env python3
"""Translate Lion's MPW 68K assembly (libs/*.asm) into GNU as syntax.

Handles only the subset those files use: PROC/ENDPROC, IMPORT, EQU, @local
labels, (sym).L absolute addressing, $hex, bitfield {o:w} operands and bare
register names.

usage: mpw2gas.py IN.asm OUT.s [PROC ...]   (PROC names limit the output)
"""
import re, sys

REG = r'(?<![\w$.])(?:([AaDd])([0-7])|(SP|sp))(?![\w])'

def regs(text):
    def r(m):
        if m.group(3):
            return '%sp'
        return '%' + m.group(1).lower() + m.group(2)
    return re.sub(REG, r, text)

def translate(src, wanted):
    out = ['| Generated by tools/mpw2gas.py from ' + sys.argv[1].split('/')[-1],
           '| Do not edit by hand; regenerate instead.',
           '\t.text']
    proc = None
    keep = False
    for raw in src.splitlines():
        line = raw.rstrip()
        code, _, comment = line.partition(';')
        code = code.rstrip()
        comment = comment.strip()
        s = code.strip()
        if not s:
            if keep or proc is None:
                out.append('\t| ' + comment if comment else '')
            continue
        up = s.split()[0].upper()
        if up in ('CASE', 'MACHINE', 'IMPORT', 'END', 'INCLUDE', 'PRINT'):
            continue
        m = re.match(r'^(\w+)\s+EQU\s+(.+)$', s, re.I)
        if m:
            out.append('\t.set\t%s,%s' % (m.group(1), m.group(2).replace('$', '0x')))
            continue
        m = re.match(r'^(\w+)\s+PROC\s+EXPORT', s, re.I)
        if m:
            proc = m.group(1)
            keep = not wanted or proc in wanted
            if keep:
                out += ['', '\t.globl\t' + proc, '\t.align\t2', proc + ':']
            continue
        if up in ('ENDPROC', 'ENDP'):
            proc = None
            continue
        if not keep:
            continue
        # local labels
        s = re.sub(r'@(\w+)', lambda m: '.L%s_%s' % (proc, m.group(1)), s)
        if not code[0].isspace():          # label in column 1
            out.append(s + ':')
            continue
        parts = s.split(None, 1)
        op = parts[0].lower().replace('moveq.l', 'moveq')
        args = parts[1] if len(parts) > 1 else ''
        args = re.sub(r'\((\w+)\)\.L', r'\1', args)           # (sym).L -> sym
        args = args.replace('$', '0x')
        args = re.sub(r'\{(\d+):(\d+)\}', r'{#\1:#\2}', args)  # bitfields
        args = regs(args)
        args = re.sub(r'\s*,\s*', ',', args)
        text = '\t%s\t%s' % (op, args) if args else '\t' + op
        if comment:
            text += '\t\t| ' + comment
        out.append(text)
    return '\n'.join(out) + '\n'

if __name__ == '__main__':
    src = open(sys.argv[1], encoding='mac_roman').read().replace('\r', '\n')
    open(sys.argv[2], 'w').write(translate(src, set(sys.argv[3:])))
