| Generated by tools/mpw2gas.py from 68KAsm.asm
| Do not edit by hand; regenerate instead.
	.text

	.set	kHiResPadBytes,32

	| -----------------------------------------------

	| void Blit320WidthMed (void *src, void *dst, long rowBytes,
	| long rows, long width, long sourceSkip);

	| Blits "width" pixels into "dst" buffer, then blasts the same
	| row into the following destination row.


	.globl	Blit320WidthMed
	.align	2
Blit320WidthMed:

	| Register usage:
	| A0			source pointer
	| A1			dest pointer #1
	| A2			dest pointer #2
	| D0			row count (-1 for dbra)
	| D1			column counter
	| D2			column counter raw (width)
	| D3			sourceSkip
	| D4			destination width (rowBytes)
	| D5			temporary values
	| D6			offset to beginning of next destination for A1 & A2

	link	%a6,#0
	movem.l	%a0-%a2/%d0-%d6,-(%sp)

	movea.l	8(%a6),%a0		| get source pointer
	movea.l	12(%a6),%a1		| get destination pointer
	move.l	16(%a6),%d4		| get rowBytes
	move.l	20(%a6),%d0		| get rows to do
	ble.s	.LBlit320WidthMed_AbsolutelyFinished		| No rows to do!
	move.l	24(%a6),%d2		| get width
	ble.s	.LBlit320WidthMed_AbsolutelyFinished		| No columns to do!
	move.l	28(%a6),%d3		| get sourceSkip
	subq.l	#1,%d0		| for "dbra" (rows)

	move.l	%d4,%d6		| rowBytes
	asl.l	#1,%d6		| * 2
	sub.l	%d2,%d6		| minus width

	movea.l	%a1,%a2		| copy dest pointer
	add.l	%d4,%a2		| point to next row

.LBlit320WidthMed_RowLoop:
	move.l	%d2,%d1		| column count
	lsr.l	#4,%d1		| / 16
	subq.l	#1,%d1		| -1 for "dbra"
	ble.s	.LBlit320WidthMed_Singles

.LBlit320WidthMed_Move16Bytes:
	move.l	(%a0)+,%d5		| Move 16 bytes into destinations
	move.l	%d5,(%a1)+
	move.l	%d5,(%a2)+
	move.l	(%a0)+,%d5
	move.l	%d5,(%a1)+
	move.l	%d5,(%a2)+
	move.l	(%a0)+,%d5
	move.l	%d5,(%a1)+
	move.l	%d5,(%a2)+
	move.l	(%a0)+,%d5
	move.l	%d5,(%a1)+
	move.l	%d5,(%a2)+

	dbra	%d1,.LBlit320WidthMed_Move16Bytes

.LBlit320WidthMed_Singles:
	move.l	%d2,%d1		| column count
	beq.s	.LBlit320WidthMed_NoSingles
	andi.l	#0xF,%d1		| mod 16
	subq.l	#1,%d1		| -1 for "dbra"
	ble.s	.LBlit320WidthMed_NoSingles

.LBlit320WidthMed_Move1Byte:
	move.b	(%a0)+,%d5
	move.b	%d5,(%a1)+
	move.b	%d5,(%a2)+

	dbra	%d1,.LBlit320WidthMed_Move1Byte

.LBlit320WidthMed_NoSingles:
	add.l	%d3,%a0
	add.l	%d6,%a1
	add.l	%d6,%a2
	dbra	%d0,.LBlit320WidthMed_RowLoop

.LBlit320WidthMed_AbsolutelyFinished:
	movem.l	(%sp)+,%a0-%a2/%d0-%d6
	unlk	%a6
	rts


	| -----------------------------------------------

	| unsigned long AsmSwapLong (unsigned long long2flip);

	| Flips the bytes from Intel format to 68000 format in a long word,
	| or vice versa.


	| -----------------------------------------------

	| unsigned word AsmSwapShort (unsigned word word2flip);

	| Flips the bytes from Intel format to 68000 format in a
	| two-byte word, or vice versa.


	| -----------------------------------------------


	.globl	Blit640SkipWidth
	.align	2
Blit640SkipWidth:


	| void Blit640SkipWidth (void *src, void *dst, long rowBytes, long rows, long width,
	| long sourceSkip)



	link	%a6,#0
	movem.l	%a0-%a1/%d0-%d6,-(%sp)

	| Register Usage:

	| A0 = srcPtr
	| A1 = dstPtr
	| D0 = row count
	| D1 = col count
	| D2 = work register
	| D3 = row bytes
	| D4 = 2nd work register
	| D5 = Copy of long word column count

	move.l	8(%a6),%a0
	move.l	12(%a6),%a1
	move.l	16(%a6),%d3		| Row bytes
	move.l	24(%a6),%d1		| columns wide

	asl.l	#1,%d3		| 2 rowbytes each pointer

	asr.l	#2,%d1		| convert "columns wide" to long words
	move.l	%d1,%d6		| store a copy
	subq.l	#1,%d1		| minus one.
	move.l	%d1,%d5		| store a copy

	asl.l	#3,%d6		| convert back to bytes * 2 (pixel-doubling)
	sub.l	%d6,%d3		| 2 rowbytes - 1 byte-based column count

	move.l	28(%a6),%d6		| sourceSkip

	move.l	20(%a6),%d0		| Number of rows to do
	subq.l	#1,%d0		| minus one for "dbra"
.LBlit640SkipWidth_RowLoop:

	move.l	%d5,%d1		| number of long words (source)
.LBlit640SkipWidth_ColLoop:

	| 8 output bytes, 4 source bytes

	move.l	(%a0)+,%d4

	rol.l	#8,%d4		| Get byte 1
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	rol.l	#8,%d2
	rol.l	#8,%d4		| Get byte 2
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	move.l	%d2,(%a1)+

	rol.l	#8,%d4		| Get byte 3
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	rol.l	#8,%d2
	rol.l	#8,%d4		| Get byte 4
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	move.l	%d2,(%a1)+

	dbra	%d1,.LBlit640SkipWidth_ColLoop

	add.l	%d3,%a1		| Dest += Offset bytes
	add.l	%d6,%a0		| src += sourceSkip

	dbra	%d0,.LBlit640SkipWidth_RowLoop

	movem.l	(%sp)+,%a0-%a1/%d0-%d6
	unlk	%a6
	rts


	| -----------------------------------------------


	.globl	Blit640Width
	.align	2
Blit640Width:


	| void Blit640Width (void *src, void *dst, long rowBytes, long rows, long width,
	| long sourceSkip)



	link	%a6,#0
	movem.l	%a0-%a2/%d0-%d7,-(%sp)

	| Register Usage:

	| A0 = srcPtr
	| A1 = dstPtr
	| A2 = 2ndDstPtr
	| D0 = row count
	| D1 = col count
	| D2 = work register
	| D3 = row bytes
	| D4 = 2nd work register
	| D5 = 3rd work register
	| D6 = source skip
	| D7 = Copy of long word column count

	move.l	8(%a6),%a0
	move.l	12(%a6),%a1
	move.l	16(%a6),%d3		| Row bytes
	move.l	24(%a6),%d1		| columns wide
	move.l	%a1,%a2
	adda.l	%d3,%a2		| add 1 full "rowbytes"

	asl.l	#1,%d3		| 2 rowbytes each pointer

	asr.l	#2,%d1		| convert "columns wide" to long words
	move.l	%d1,%d6		| store a copy
	subq.l	#1,%d1		| minus one.
	move.l	%d1,%d7		| store a copy

	asl.l	#3,%d6		| convert back to bytes * 2 (pixel-doubling)
	sub.l	%d6,%d3		| 2 rowbytes - 1 byte-based column count

	move.l	28(%a6),%d6		| sourceSkip

	move.l	20(%a6),%d0		| Number of rows to do
	subq.l	#1,%d0		| minus one for "dbra"
.LBlit640Width_RowLoop:

	move.l	%d7,%d1		| number of long words (source)
.LBlit640Width_ColLoop:

	| 8 output bytes, 4 source bytes

	move.l	(%a0)+,%d4

	move.l	%d4,%d5		| d5 = 4,3,2,1
	move.l	%d4,%d2		| d2 = 4,3,2,1
	swap	%d5		| d5 = 2,1,4,3
	move.w	%d5,%d2		| d2 = 4,3,4,3
	move.w	%d4,%d5		| d5 = 2,1,2,1
	rol.w	#8,%d2		| d2 = 4,3,3,4
	rol.w	#8,%d5		| d5 = 2,1,1,2
	ror.l	#8,%d2		| d2 = 4,4,3,3
	ror.l	#8,%d5		| d5 = 2,2,1,1

	move.l	%d2,(%a1)+		| Write out 4433,4433
	move.l	%d2,(%a2)+

	move.l	%d5,(%a1)+		| Write out 2211,2211
	move.l	%d5,(%a2)+

	dbra	%d1,.LBlit640Width_ColLoop

	add.l	%d3,%a1		| Dest += Offset bytes
	add.l	%d3,%a2
	add.l	%d6,%a0		| src += sourceSkip

	dbra	%d0,.LBlit640Width_RowLoop

	movem.l	(%sp)+,%a0-%a2/%d0-%d7
	unlk	%a6
	rts


	| -----------------------------------------------


	.globl	Blit320Width
	.align	2
Blit320Width:


	| void Blit320Width (void *src, void *dst, long rowBytes, long rows, long width,
	| long sourceSkip)



	| Register Usage:

	| A0 = srcPtr
	| A1 = dstPtr
	| D0 = row count
	| D1 = col repeat count
	| D2 = row bytes
	| D3 = rows
	| D4 = source skip

	link	%a6,#0
	movem.l	%a0-%a1/%d0-%d6,-(%sp)

	movea.l	8(%a6),%a0		| src pointer
	movea.l	12(%a6),%a1		| dst pointer
	move.l	16(%a6),%d2		| row bytes
	move.l	24(%a6),%d1		| columns wide (width)
	move.l	28(%a6),%d4		| source skip

	lsr.l	#3,%d1
	lsl.l	#3,%d1
	sub.l	%d1,%d2		| row bytes - columns wide
	asr.l	#2,%d1		| / 4 = long words to move

	move.l	%d1,%d6		| store in D6
	andi.l	#7,%d6		| "singles" 0-7 long words
	subq.l	#1,%d6		| for dbra instruction

	lsr.l	#3,%d1		| / 8 = 32-byte packets to move
	subq.l	#1,%d1		| minus 1 for dbra
	move.l	%d1,%d5		| copy into D5: (longWords2Move - 1)

	move.l	20(%a6),%d0		| rows
	subq.l	#1,%d0		| minus 1 for dbra
.LBlit320Width_RowLoop:
	move.l	%d5,%d1		| 32-byte packets to move - 1
	ble.s	.LBlit320Width_Singles		| if <= 0, do singles
.LBlit320Width_Col16Loop:
	move.l	(%a0)+,(%a1)+
	move.l	(%a0)+,(%a1)+
	move.l	(%a0)+,(%a1)+
	move.l	(%a0)+,(%a1)+
	move.l	(%a0)+,(%a1)+
	move.l	(%a0)+,(%a1)+
	move.l	(%a0)+,(%a1)+
	move.l	(%a0)+,(%a1)+
	dbra	%d1,.LBlit320Width_Col16Loop
.LBlit320Width_Singles:
	move.l	%d6,%d1
	ble.s	.LBlit320Width_NextRow
.LBlit320Width_ColLoop:
	move.l	(%a0)+,(%a1)+
	dbra	%d1,.LBlit320Width_ColLoop
.LBlit320Width_NextRow:
	adda.l	%d4,%a0		| source += sourceSkip
	adda.l	%d2,%a1		| Point to next dest row
	dbra	%d0,.LBlit320Width_RowLoop

.LBlit320Width_Done:
	movem.l	(%sp)+,%a0-%a1/%d0-%d6
	unlk	%a6
	rts


	| -----------------------------------------------


	.globl	Blit320Small
	.align	2
Blit320Small:


	| void Blit320Small (void *src, void *dst, long rowBytes, long rows)



	| Register Usage:

	| A0 = srcPtr
	| A1 = dstPtr
	| D0 = row count
	| D1 = col repeat count
	| D2 = row bytes
	| D3-D6 = temp registers


	link	%a6,#0
	movem.l	%a0-%a1/%d0-%d7,-(%sp)

	movea.l	8(%a6),%a0
	movea.l	12(%a6),%a1

	move.l	16(%a6),%d1		| row bytes
	sub.l	#320,%d1		| minus 320

	move.l	20(%a6),%d0		| rows
	subq.l	#1,%d0
.LBlit320Small_RowLoop:
	movem.l	%d0-%d1,-(%sp)

	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1

	movem.l	(%sp)+,%d0-%d1
	adda.l	%d1,%a1		| Point to next dest row
	dbra	%d0,.LBlit320Small_RowLoop

	movem.l	(%sp)+,%a0-%a1/%d0-%d7
	unlk	%a6
	rts


	| -----------------------------------------------


	.globl	Blit320
	.align	2
Blit320:


	| void Blit320 (void *src, void *dst, long rowBytes, long rows)



	| Register Usage:

	| A0 = srcPtr
	| A1 = dstPtr
	| D0 = row count
	| D1 = col repeat count
	| D2 = row bytes
	| D3-D6 = temp registers


	link	%a6,#0
	movem.l	%a0-%a1/%d0-%d7,-(%sp)

	movea.l	8(%a6),%a0
	movea.l	12(%a6),%a1

	move.l	16(%a6),%d1		| row bytes
	sub.l	#320,%d1		| minus 320

	move.l	20(%a6),%d0		| rows
	subq.l	#1,%d0
.LBlit320_RowLoop:
	movem.l	%d0-%d1,-(%sp)

	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1
	movem.l	(%a0)+,%d0-%d7		| 32 bytes
	movem.l	%d0-%d7,(%a1)
	adda.l	#32,%a1

	movem.l	(%sp)+,%d0-%d1
	adda.l	#kHiResPadBytes,%a0		| Pad bytes
	adda.l	%d1,%a1		| Point to next dest row
	dbra	%d0,.LBlit320_RowLoop

	movem.l	(%sp)+,%a0-%a1/%d0-%d7
	unlk	%a6
	rts


	| -----------------------------------------------


	.globl	Blit640
	.align	2
Blit640:


	| void Blit640 (void *src, void *dst, long rowBytes, long rows)



	link	%a6,#0
	movem.l	%a0-%a2/%d0-%d7,-(%sp)

	| Register Usage:

	| A0 = srcPtr
	| A1 = dstPtr
	| A2 = 2ndDstPtr
	| D0 = row count
	| D1 = col count
	| D2 = work register
	| D3 = row bytes
	| D4 = 2nd work register

	move.l	8(%a6),%a0
	move.l	12(%a6),%a1
	move.l	16(%a6),%d3
	move.l	%a1,%a2
	add.l	%d3,%a2
	asl.l	#1,%d3
	sub.l	#640,%d3

	move.l	20(%a6),%d0
	subq.l	#1,%d0
.LBlit640_RowLoop:

	move.l	#39,%d1		| 40 * 16 = 640
.LBlit640_ColLoop:

	| 8 output bytes, 4 source bytes

	move.l	(%a0)+,%d4

	move.l	%d4,%d5		| d5 = 4,3,2,1
	move.l	%d4,%d2		| d2 = 4,3,2,1
	swap	%d5		| d5 = 2,1,4,3
	move.w	%d5,%d2		| d2 = 4,3,4,3
	move.w	%d4,%d5		| d5 = 2,1,2,1
	rol.w	#8,%d2		| d2 = 4,3,3,4
	rol.w	#8,%d5		| d5 = 2,1,1,2
	ror.l	#8,%d2		| d2 = 4,4,3,3
	ror.l	#8,%d5		| d5 = 2,2,1,1

	move.l	%d2,(%a1)+		| Write out 4433,4433
	move.l	%d2,(%a2)+

	move.l	%d5,(%a1)+		| Write out 2211,2211
	move.l	%d5,(%a2)+

	| 8 output bytes, 4 source bytes

	move.l	(%a0)+,%d4

	move.l	%d4,%d5		| d5 = 4,3,2,1
	move.l	%d4,%d2		| d2 = 4,3,2,1
	swap	%d5		| d5 = 2,1,4,3
	move.w	%d5,%d2		| d2 = 4,3,4,3
	move.w	%d4,%d5		| d5 = 2,1,2,1
	rol.w	#8,%d2		| d2 = 4,3,3,4
	rol.w	#8,%d5		| d5 = 2,1,1,2
	ror.l	#8,%d2		| d2 = 4,4,3,3
	ror.l	#8,%d5		| d5 = 2,2,1,1

	move.l	%d2,(%a1)+		| Write out 4433,4433
	move.l	%d2,(%a2)+

	move.l	%d5,(%a1)+		| Write out 2211,2211
	move.l	%d5,(%a2)+

	dbra	%d1,.LBlit640_ColLoop

	add.l	%d3,%a1
	add.l	%d3,%a2

	dbra	%d0,.LBlit640_RowLoop

	movem.l	(%sp)+,%a0-%a2/%d0-%d7
	unlk	%a6
	rts


	| -----------------------------------------------


	.globl	Blit640Skip
	.align	2
Blit640Skip:


	| void Blit640Skip (void *src, void *dst, long rowBytes, long rows)



	link	%a6,#0
	movem.l	%a0-%a3/%d0-%d7,-(%sp)

	| Register Usage:

	| A0 = srcPtr
	| A1 = dstPtr
	| D0 = row count
	| D1 = col count
	| D2 = work register
	| D3 = row bytes
	| D4 = 2nd work register

	move.l	8(%a6),%a0
	move.l	12(%a6),%a1
	move.l	16(%a6),%d3
	sub.l	#640,%d3

	move.l	20(%a6),%d0
	subq.l	#1,%d0
.LBlit640Skip_RowLoop:

	move.l	#39,%d1		| 40 * 16 = 640
.LBlit640Skip_ColLoop:

	| 8 output bytes, 4 source bytes

	move.l	(%a0)+,%d4

	rol.l	#8,%d4		| Get byte 1
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	rol.l	#8,%d2
	rol.l	#8,%d4		| Get byte 2
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	move.l	%d2,(%a1)+

	rol.l	#8,%d4		| Get byte 3
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	rol.l	#8,%d2
	rol.l	#8,%d4		| Get byte 4
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	move.l	%d2,(%a1)+

	| 8 output bytes, 4 source bytes

	move.l	(%a0)+,%d4

	rol.l	#8,%d4		| Get byte 1
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	rol.l	#8,%d2
	rol.l	#8,%d4		| Get byte 2
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	move.l	%d2,(%a1)+

	rol.l	#8,%d4		| Get byte 3
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	rol.l	#8,%d2
	rol.l	#8,%d4		| Get byte 4
	move.b	%d4,%d2
	rol.l	#8,%d2
	move.b	%d4,%d2
	move.l	%d2,(%a1)+

	dbra	%d1,.LBlit640Skip_ColLoop

	add.l	%d3,%a1
	add.l	%d3,%a1
	add.l	#640,%a1

	dbra	%d0,.LBlit640Skip_RowLoop

	movem.l	(%sp)+,%a0-%a3/%d0-%d7
	unlk	%a6
	rts


