| Generated by tools/mpw2gas.py from Draw68K.asm
| Do not edit by hand; regenerate instead.
	.text



	.set	SCREENWIDTH,320
	.set	HIRESWIDTH,672

	| -----------------------------------------------

	| void R_DrawColumn68KLowRes (void);

	| Same as the C version, only a little quicker for
	| 68K-based Macintoshes.



	.globl	R_DrawColumn68KLowRes
	.align	2
R_DrawColumn68KLowRes:

	movem.l	%a0-%a2/%d0-%d7,-(%sp)
	move.l	dc_yh,%d3
	move.l	dc_yl,%d2
	sub.l	%d2,%d3
	bmi	.LR_DrawColumn68KLowRes_L1

	lea	columnofs,%a1
	move.l	dc_x,%d1
	move.l	(%a1,%d1.L*4),%a1
	lea	ylookup,%a0
	add.l	(%a0,%d2.L*4),%a1

	move.l	dc_iscale,%d4
	sub.l	centery,%d2
	muls.l	%d4,%d2
	add.l	dc_texturemid,%d2

	| d0 scratch offset / pixel 1
	| d1 qaud count
	| d2 frac 1
	| d3 count
	| d4 fracstep
	| d5 SCREENWIDTH
	| d6 frac 2
	| d7 scratch 2

	| a0 source
	| a1 dest
	| a2 colormap

	move.l	dc_source,%a0
	move.l	dc_colormap,%a2

	addq.l	#1,%d3
	move.l	%d3,%d1
	lsr.l	#2,%d1
	beq.s	.LR_DrawColumn68KLowRes_Lcsinglestart
	subq.l	#1,%d1

	bfextu	%d2{#9:#7},%d0		| feed the first step of the pipeline
	move.l	%d2,%d6
	add.l	%d4,%d6		| put D6 a step ahead of D2
	lsl.l	#1,%d4		| make the step a double

	move.l	#SCREENWIDTH*4,%d5

.LR_DrawColumn68KLowRes_Lcquadloop:
	bfextu	%d6{#9:#7},%d7
	move.b	(%a0,%d0.w),%d0
	add.l	%d4,%d2
	move.b	(%a0,%d7.w),%d7
	add.l	%d4,%d6
	move.b	(%a2,%d0.w),(%a1)
	bfextu	%d2{#9:#7},%d0
	move.b	(%a2,%d7.w),SCREENWIDTH(%a1)

	bfextu	%d6{#9:#7},%d7
	move.b	(%a0,%d0.w),%d0
	add.l	%d4,%d2
	move.b	(%a0,%d7.w),%d7
	add.l	%d4,%d6
	move.b	(%a2,%d0.w),SCREENWIDTH*2(%a1)
	bfextu	%d2{#9:#7},%d0
	move.b	(%a2,%d7.w),SCREENWIDTH*3(%a1)

	add.l	%d5,%a1
	dbra	%d1,.LR_DrawColumn68KLowRes_Lcquadloop

	lsr.l	#1,%d4		| put the step value back to singles

.LR_DrawColumn68KLowRes_Lcsinglestart:
	andi.l	#3,%d3
	beq.s	.LR_DrawColumn68KLowRes_L1		| no extras
	move.l	#SCREENWIDTH,%d5
	subq.l	#1,%d3

.LR_DrawColumn68KLowRes_Lcsingleloop:
	bfextu	%d2{#9:#7},%d0
	move.b	(%a0,%d0.w),%d0
	add.l	%d4,%d2
	move.b	(%a2,%d0.w),(%a1)

	add.l	%d5,%a1
	dbra	%d3,.LR_DrawColumn68KLowRes_Lcsingleloop

.LR_DrawColumn68KLowRes_L1:
	movem.l	(%sp)+,%a0-%a2/%d0-%d7
	rts


	| -----------------------------------------------

	| void R_DrawColumn68KHiRes (void);

	| Same as the C version, only a little quicker for
	| 68K-based Macintoshes.



	.globl	R_DrawColumn68KHiRes
	.align	2
R_DrawColumn68KHiRes:

	movem.l	%a0-%a2/%d0-%d7,-(%sp)
	move.l	dc_yh,%d3
	move.l	dc_yl,%d2
	sub.l	%d2,%d3
	bmi	.LR_DrawColumn68KHiRes_L1

	lea	columnofs,%a1
	move.l	dc_x,%d1
	move.l	(%a1,%d1.L*4),%a1
	lea	ylookup,%a0
	add.l	(%a0,%d2.L*4),%a1

	move.l	dc_iscale,%d4
	sub.l	centery,%d2
	muls.l	%d4,%d2
	add.l	dc_texturemid,%d2

	| d0 scratch offset / pixel 1
	| d1 qaud count
	| d2 frac 1
	| d3 count
	| d4 fracstep
	| d5 SCREENWIDTH
	| d6 frac 2
	| d7 scratch 2

	| a0 source
	| a1 dest
	| a2 colormap

	move.l	dc_source,%a0
	move.l	dc_colormap,%a2

	addq.l	#1,%d3
	move.l	%d3,%d1
	lsr.l	#2,%d1
	beq.s	.LR_DrawColumn68KHiRes_Lcsinglestart
	subq.l	#1,%d1

	bfextu	%d2{#9:#7},%d0		| feed the first step of the pipeline
	move.l	%d2,%d6
	add.l	%d4,%d6		| put D6 a step ahead of D2
	lsl.l	#1,%d4		| make the step a double

	move.l	#HIRESWIDTH*4,%d5

.LR_DrawColumn68KHiRes_Lcquadloop:
	bfextu	%d6{#9:#7},%d7
	move.b	(%a0,%d0.w),%d0
	add.l	%d4,%d2
	move.b	(%a0,%d7.w),%d7
	add.l	%d4,%d6
	move.b	(%a2,%d0.w),(%a1)
	bfextu	%d2{#9:#7},%d0
	move.b	(%a2,%d7.w),HIRESWIDTH(%a1)

	bfextu	%d6{#9:#7},%d7
	move.b	(%a0,%d0.w),%d0
	add.l	%d4,%d2
	move.b	(%a0,%d7.w),%d7
	add.l	%d4,%d6
	move.b	(%a2,%d0.w),HIRESWIDTH*2(%a1)
	bfextu	%d2{#9:#7},%d0
	move.b	(%a2,%d7.w),HIRESWIDTH*3(%a1)

	add.l	%d5,%a1
	dbra	%d1,.LR_DrawColumn68KHiRes_Lcquadloop

	lsr.l	#1,%d4		| put the step value back to singles

.LR_DrawColumn68KHiRes_Lcsinglestart:
	andi.l	#3,%d3
	beq.s	.LR_DrawColumn68KHiRes_L1		| no extras
	move.l	#HIRESWIDTH,%d5
	subq.l	#1,%d3

.LR_DrawColumn68KHiRes_Lcsingleloop:
	bfextu	%d2{#9:#7},%d0
	move.b	(%a0,%d0.w),%d0
	add.l	%d4,%d2
	move.b	(%a2,%d0.w),(%a1)

	add.l	%d5,%a1
	dbra	%d3,.LR_DrawColumn68KHiRes_Lcsingleloop

.LR_DrawColumn68KHiRes_L1:
	movem.l	(%sp)+,%a0-%a2/%d0-%d7
	rts


	| -----------------------------------------------

	| void R_DrawSpanAsm (void);

	| Same as the C version, only a little quicker for
	| 68K-based Macintoshes.



	.globl	R_DrawSpanAsm
	.align	2
R_DrawSpanAsm:

	movem.l	%a2/%d2-%d7,-(%sp)

	move.l	ds_x2,%d7
	cmp.l	ds_x1,%d7
	move.l	ds_y,%d1
	lea	ylookup,%a1
	move.l	ds_x1,%d0
	lea	columnofs,%a0
	move.l	(%a1,%d1.L*4),%a1
	add.l	(%a0,%d0.L*4),%a1
	move.l	ds_x2,%d3
	sub.l	ds_x1,%d3

	| d0 extracted yfrac / composite
	| d1 extracted xfrac
	| d2 xfrac yfrac
	| d3 loop count
	| d4 xstep ystep
	| d5 pixel
	| d6 quad count

	| a0 ds_source
	| a1 dest
	| a2 ds_colormap

	moveq	#0,%d5
	move.l	ds_source,%a0
	move.l	ds_colormap,%a2

	| build frac

	move.l	ds_yfrac,%d2
	moveq	#10,%d0
	lsl.l	%d0,%d2
	clr.w	%d2		| andi.l	#$FFFF0000,D2
	move.l	ds_xfrac,%d0
	lsr.l	#6,%d0
	andi.l	#0xFFFF,%d0
	add.l	%d0,%d2

	| build step

	move.l	ds_ystep,%d4
	moveq	#10,%d0
	lsl.l	%d0,%d4
	clr.w	%d4		| andi.l	$FFFF0000,D4
	move.l	ds_xstep,%d0
	lsr.l	#6,%d0
	andi.l	#0xFFFF,%d0
	add.l	%d0,%d4

	addq.l	#1,%d3
	move.l	%d3,%d6
	lsr.l	#2,%d6
	beq.s	.LR_DrawSpanAsm_Lsinglestart
	subq.l	#1,%d6

.LR_DrawSpanAsm_Lquadloop:
	bfextu	%d2{#0:#6},%d0		| extract y
	bfextu	%d2{#16:#6},%d1		| extract x
	lsl.l	#6,%d0
	add.l	%d1,%d0
	add.l	%d4,%d2		| advance fraction
	move.b	(%a0,%d0.w),%d5		| get source pixel
	move.b	(%a2,%d5.w),(%a1)+		| translate and write out to dest

	bfextu	%d2{#0:#6},%d0		| extract y
	bfextu	%d2{#16:#6},%d1		| extract x
	lsl.l	#6,%d0
	add.l	%d1,%d0
	add.l	%d4,%d2		| advance fraction
	move.b	(%a0,%d0.w),%d5		| get source pixel
	move.b	(%a2,%d5.w),(%a1)+		| translate and write out to dest

	bfextu	%d2{#0:#6},%d0		| extract y
	bfextu	%d2{#16:#6},%d1		| extract x
	lsl.l	#6,%d0
	add.l	%d1,%d0
	add.l	%d4,%d2		| advance fraction
	move.b	(%a0,%d0.w),%d5		| get source pixel
	move.b	(%a2,%d5.w),(%a1)+		| translate and write out to dest

	bfextu	%d2{#0:#6},%d0		| extract y
	bfextu	%d2{#16:#6},%d1		| extract x
	lsl.l	#6,%d0
	add.l	%d1,%d0
	add.l	%d4,%d2		| advance fraction
	move.b	(%a0,%d0.w),%d5		| get source pixel
	move.b	(%a2,%d5.w),(%a1)+		| translate and write out to dest

	dbra	%d6,.LR_DrawSpanAsm_Lquadloop

.LR_DrawSpanAsm_Lsinglestart:
	andi.l	#3,%d3
	beq.s	.LR_DrawSpanAsm_Ldone		| no extras
	subq.l	#1,%d3

.LR_DrawSpanAsm_Lsingleloop:
	bfextu	%d2{#0:#6},%d0		| extract y
	bfextu	%d2{#16:#6},%d1		| extract x
	lsl.l	#6,%d0
	add.l	%d1,%d0
	add.l	%d4,%d2		| advance fraction
	move.b	(%a0,%d0.w),%d5		| get source pixel
	move.b	(%a2,%d5.w),(%a1)+		| translate and write out to dest

	dbra	%d3,.LR_DrawSpanAsm_Lsingleloop

.LR_DrawSpanAsm_Ldone:
	movem.l	(%sp)+,%a2/%d2-%d7
	rts


